Update entry encryption to encrypt tar of files

diff --git a/lib/migration b/lib/migration
--- a/lib/migration
+++ b/lib/migration
@@ -1,10 +1,45 @@
-check_and_migrate_format() {
-  [[ ! -f "$JOURNAL_DIR/.journal/migrated" ]] && migrate_journal_format
+requires_migration() {
+  [[ ! -f "$(version_file_path)" || "$(cat $(version_file_path))" != "$VERSION" ]]
 }
 
-migrate_format() {
-  for file in $JOURNAL_DIR/*/*/*; do
-    true
+migrate_journal_format() {
+  retrieve_or_read_passphrase
+  for entry_dir in $JOURNAL_DIR/*/*/*; do
+    log_info "Migrating entry for $(echo $entry_dir | extract_date_from_path)"
+
+    old_decrypt_dir $entry_dir || return 1
+    for file in $entry_dir/**/*.gpg; do
+      shred_file $file
+    done
+    encrypt_dir $entry_dir
+  done
+
+  mkdir -p "$(dirname $(version_file_path))"
+  echo $VERSION > "$(version_file_path)"
+}
+
+old_decrypt_dir() {
+  local file
+  for file in $1/**/*.gpg; do
+    old_decrypt_file $file
+    if [[ $? -eq 2 ]]; then
+      log_error "Failed to decrypt $file, check key"
+      return 1
+    fi
   done
 }
 
+old_decrypt_file() {
+  local file="$1"
+  local decrypted_file="${file/.gpg/}"
+  if [[ -f "$decrypted_file" ]]; then
+    return 1
+  fi
+
+  if ! ( \
+    gpg -d -o "$decrypted_file" --batch \
+    --passphrase "$PASSPHRASE" "$file" > /dev/null 2>&1 \
+  ); then
+    return 2
+  fi
+}
